import type { FullFormData } from '../types/form';

export const defaultFormData: FullFormData = {
  anamnese: {
    patientName: '',
    birthDate: '',
    ageYearsMonths: '',
    education: '',
    referralProfessional: '',
    gender: '',
    plannedPregnancy: 'SIM',
    motherAgeAtPregnancy: '',
    fatherAgeAtPregnancy: '',
    calmPregnancy: 'SIM',
    familyAccepted: 'SIM',
    prenatalCare: 'SIM',
    deliveryType: 'NORMAL',
    deliveryComplications: 'NÃO',
    prematureOrFullTerm: 'A TERMO',
    cryingBaby: 'NÃO',
    hasSiblings: 'NÃO',
    siblingsCount: '',
    parentsDrugUse: 'NÃO',
    breastfeedingDuration: '',
    crawled: 'SIM',
    usedWalker: 'NÃO',
    ageStartedWalking: '',
    speechDelay: 'NÃO',
    dictionProblems: 'NÃO',
    dictionNotes: '',
    ageStartedSchool: '',
    smoothSchoolAdaptation: 'SIM',
    favoriteChildhoodGames: '',
    neonatalJaundice: 'NÃO',
    hadCovid: '',
    motherCandidiasis: '',
    usedPacifier: 'NÃO',
    pacifierUntilAge: '',
    transitionalObject: 'NÃO',
    phoneCallDifficulty: 'NÃO',
    gastrointestinalProblems: 'NÃO',
    diabetes: 'NÃO',
    sleepProblems: 'NÃO',
    bodyPain: 'NÃO',
    familyAutism: 'NÃO',
    dizziness: 'NÃO',
    fearfulChild: 'NÃO',
    noDangerAwareness: 'NÃO',
    interestInOthers: 'SIM',
    otherDiagnoses: 'NÃO',
    whichDiagnoses: '',
    takesMedication: 'NÃO',
    whichMedication: '',
    alwaysTired: 'NÃO',
  },
  tdah: {
    tdah1: 'Nunca / Raramente',
    tdah2: 'Nunca / Raramente',
    tdah3: 'Nunca / Raramente',
    tdah4: 'Nunca / Raramente',
    tdah5: 'Nunca / Raramente',
    tdah6: 'Nunca / Raramente',
    tdah7: 'Nunca / Raramente',
    tdah8: 'Nunca / Raramente',
    tdah9: 'Nunca / Raramente',
    tdah10: 'Nunca / Raramente',
    tdah11: 'Nunca / Raramente',
    tdah12: 'Nunca / Raramente',
    tdah13: 'Nunca / Raramente',
    tdah14: 'Nunca / Raramente',
  },
  tea: {
    tea1: 'Não',
    tea2: 'Não',
    tea3: 'Não',
    tea4: 'Não',
    tea5: 'Não',
    tea6: 'Não',
    tea7: 'Não',
    tea8: 'Não',
    tea9: 'Não',
    tea10: 'Não',
    tea11: 'Não',
    tea12: 'Não',
  },
};
